-- 1
BEGIN;
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;
SHOW TRANSACTION ISOLATION LEVEL;
SELECT sum(rating) FROM pizzeria;

SELECT sum(rating) FROM pizzeria;
COMMIT;

SELECT sum(rating) FROM pizzeria;

-- 2
BEGIN;
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;
SHOW TRANSACTION ISOLATION LEVEL;

UPDATE pizzeria SET rating = 5.0 WHERE name = 'Pizza Hut';
COMMIT;

SELECT sum(rating) FROM pizzeria;